### ISSUE TITLE
Outlook Plugin not working when LDAP Authentication enabled

### ISSUE THREAD

**Issue by gunnicom** [salesagility/SuiteCRM-Outlook-Plugin#6] opened 2016-01-25 13:57 UTC
When enabling ldap authentication login for the outlook plugin, it does not work.
It does work for my admin account, as this account is not authed over LDAP.
All normal user accounts do not work.

Additional info:
In modules\Users\authentication\LDAPAuthenticate\LDAPAuthenticateUser.php , function authenticateUser
When i log in normal through web interface, the $password variable seems filled with the clear text password, whereas if the outlook plugin tries to login it is an md5 sum.

See also https://github.com/salesagility/SuiteCRM/issues/489

**Comment by CamoMacdonald** [comment] 2017-01-24 12:51
Related to Issue #23

**Comment by CamoMacdonald** [comment] 2017-02-27 16:39
@gunnicom I am closing this issue as a duplicate of #23 however this is on our roadmap to fix soon.

**Closed by CamoMacdonald** 2017-02-27 16:39 UTC
Labels: Bug, Duplicate, On Roadmap

**Comment by gunnicom** [comment] 2017-02-27 20:50
Thanks for the fast reaction. First reaction after under one year. Impressive.
